extern const char on;
extern const char off;
extern const char starL;
extern const char setY;
extern const char setX;
extern const char LA[8];
extern const char LB[8];
extern const char LC[8];
extern const char LD[8];
extern const char LE[8];
extern const char LF[8];
extern const char LG[8];
extern const char LH[8];
extern const char LI[8];
extern const char LJ[8];
extern const char LK[8];
extern const char LL[8];
extern const char LM[8];
extern const char LN[8];
extern const char LO[8];
extern const char LP[8];
extern const char LQ[8];
extern const char LR[8];
extern const char LS[8];
extern const char LT[8];
extern const char LU[8];
extern const char LV[8];
extern const char LW[8];
extern const char LX[8];
extern const char LZ[8];
extern const char NO[8];
extern const char N1[8];
extern const char N2[8];
extern const char N3[8];
extern const char N4[8];
extern const char N5[8];
extern const char N6[8];
extern const char N7[8];
extern const char N8[8];
extern const char N9[8];
extern const char NUM[10][8];
extern const char GradosChar[4];
extern const char PorcentajeChar[8];
void borradoGLCD  (int a);
void comandoGLCD  (int cs, char a);
void IniciarGLCD(void);
void SendGLCD  (int cs, char b);
void ImprimirTemperatura(void);